"$schema" = 'https://starship.rs/config-schema.json'

#palette = 'gruvbox_dark'
#format = """
#[](color_bg0)\
#$os\
#$username\
#[](fg:color_bg0 bg:color_bg1)\
#$directory\
#[](fg:color_bg1 bg:color_bg2)\
#$git_branch\
#$git_status\
#${env_var.ADE_VIEW_NAME}\
#[](fg:color_bg2 bg:color_bg3)\
#$hostname\
#[](fg:color_bg3 bg:color_bg5)\
#$conda\
#[](fg:color_bg5 bg:color_bg4)\
#$time\
#$cmd_duration\
#[ ](fg:color_bg4)\
#$line_break$character"""

palette = 'dracula'
format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
${env_var.ADE_VIEW_NAME}\
$hostname\
$conda\
$time\
$cmd_duration\
$line_break$character"""

[palettes.gruvbox_dark]
color_bg0 = '#ff6e00'
color_fg0 = '#fbf1c7'
color_bg1 = '#ffa400'
color_fg1 = '#fbf1c7'
color_bg2 = '#98971a'
color_fg2 = '#fbf1c7'
color_bg3 = '#458588'
color_fg3 = '#fbf1c7'
color_bg4 = '#3c3836'
color_fg4 = '#fbf1c7'
color_bg5 = '#665c54'
color_fg5 = '#fbf1c7'
color_purple = '#b16286'
color_red = '#cc241d'
color_green = '#98971a'
color_yellow = '#ffa400'

[palettes.dracula]
color_bg0 = "#282828"
color_fg0 = "#8be9fd"
color_bg1 = "#282828"
color_fg1 = "#50fa7b"
color_bg2 = "#282828"
color_fg2 = "#ff5555"
color_bg3 = "#282828"
color_fg3 = "#bd93f9"
color_bg4 = "#282828"
color_fg4 = "#f1fa8c"
color_bg5 = "#282828"
color_fg5 = "#ffb86c"
color_purple = '#b16286'
color_red = "#ff5555"
color_green = "#50fa7b"
color_yellow = '#ffa400'
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"

[os]
disabled = true
style = "bg:color_bg0 fg:color_fg0"
format = '[ $symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
OracleLinux = "⛁"

[username]
show_always = true
style_user = "bg:color_bg0 fg:color_fg0"
style_root = "bg:color_bg0 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_bg1"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol $branch ](fg:color_fg2 bg:color_bg2)]($style)'

[git_status]
style = "bg:color_bg2"
format = '[[($all_status$ahead_behind )](fg:color_fg2 bg:color_bg2)]($style)'

[env_var.ADE_VIEW_NAME]
disabled = false
description = 'The name of the current ADE view (if any)'
style = "fg:color_fg2 bg:color_bg2"
format = '[( $env_value )]($style)'

[hostname]
disabled = false
style = "fg:color_fg3 bg:color_bg3"
format = "[ $ssh_symbol$hostname ]($style)"

[conda]
style = "fg:color_fg5 bg:color_bg5"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg5)]($style)'

[time]
disabled = false
time_format = "%R"
utc_time_offset = '5.5'
style = "bg:color_bg4"
format = '[[  $time ](fg:color_fg4 bg:color_bg4)]($style)'

[cmd_duration]
disabled = false
style = "bold fg:yellow bg:color_bg4"
format = "[last command: $duration ]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
